### PR TITLE
store credentials file in proper location

### PR DESCRIPTION
**Pull request by jcgruenhage**
This changes the location to one provided by the directories library, which chooses a proper location based on the home path obtained from the operating system. If the old file is still there, it's being migrated to the new path.

### CODE REVIEW

**Comment by jcgruenhage** [comment]
This (and a release containing it) is also required for the void package, because the current implementation looks for /usr/bin/credentials.toml when the binary is installed properly, which is obviously not writable by non-root users

**Comment by jcgruenhage** [comment]
@gobanos hey, normally I wouldn't be so pushy, but considering that advent of code is not all year, could you take a look at this, merge it and release it as 0.3.1?

**Comment by AlisCode** [comment]
LGTM :+1:

**Comment by jcgruenhage** [comment]
Thanks for merging! Now the only thing missing for the void linux package is a release.

**Comment by gobanos** [comment]
> Thanks for merging! Now the only thing missing for the void linux package is a release.

Release 0.3.1 of `cargo-aoc` is now done :)

**Comment by jcgruenhage** [comment]
Thanks!

**Comment by jcgruenhage** [comment]
Ah, you didn't release master, right? So the license files PR from yesterday isn't included :/

**Comment by gobanos** [comment]
Erf... I do releases from 0.3 branch, master is still under refactor :/ Let's go for a 0.3.2...

**Comment by jcgruenhage** [comment]
Thanks again then :) Sorry for the trouble..

**Comment by gobanos** [comment]
0.3.2 is published ;)

**Comment by jcgruenhage** [comment]
Currently building the void package locally, will publish it if it works

**Comment by jcgruenhage** [comment]
Not sure what happened there, but the license files are still missing:

image

**Comment by jcgruenhage** [comment]
It seems that the Cargo.toml either needs to explicitly include the license files, or I could pull the release from github instead, if you tag the release in git too

**Comment by gobanos** [comment]
Is https://github.com/gobanos/cargo-aoc/tree/0.3.2 enough ?

**Comment by jcgruenhage** [comment]
https://github.com/gobanos/cargo-aoc/archive/0.3.2.tar.gz is what I needed. Thanks again!

**Pull request merged**
